-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgGAsQ2+qZKsgzlQd4
Y8XuQt6AsHWcisQxn9GFoyx6I3OgCgYIKoZIzj0DAQehRANCAATTjcLfCTGLjIBA
GYjKLJH4cNuDWaI/p87H+qthPHCAv1gpKPqDoCnEMy51N8QBcoV24++WbD+RKTAX
cE5kvLV9
-----END PRIVATE KEY-----